### ISSUE TITLE
config for hd4600

### ISSUE THREAD

**Issue by robi62** [HJebbour/HP-ProDesk-400-G1-Hackintosh-every-macOS#2]
hi have you tried with built in graphics???
I cannot get audio through HDMi or DP only internal speakers.
can you share config for hd4600 if you have it???
Thanks

**Comment by HJebbour** [comment]
Hi, I only used iGPU when I first started working on this project, I didn't play much with the built-in graphics.

**Comment by robi62** [comment]
ok thanks

**Comment by robi62** [comment]
hi will this pny card work????
![Screenshot 2024-11-13 at 13 56 28](https://github.com/user-attachments/assets/c2865f1c-7417-464b-b55c-70246484316f)
![Screenshot 2024-11-13 at 13 56 45](https://github.com/user-attachments/assets/665cc40a-d6a8-448e-a8ef-2ac584e79e1c)

**Comment by HJebbour** [comment]
Yes it should, I have the same card that made this project a success!
